# Site settings
title: D.P. O'Donnell
email: dan@dpodonnell.info
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dpodonnell.info" # the base hostname & protocol for your site

twitter_username: @danielpaulod
github_username: caedmon5

# Build settings
markdown: kramdown
